edition = "2018"

use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "max"

# TODO Awaiting stabilization
# comment_width = 100
# match_arm_blocks = false
# struct_field_align_threshold = 4
