language: rust

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      # dependencies needed to build kcov.
      # TODO Remove when kcov v34 is available.
      - libelf-dev
      - libdw-dev
      - binutils-dev
      - libiberty-dev

      # dependencies of the code coverage tool.
      - jq

script:
  - cargo build --features fatal-warnings
  - cargo test  --features fatal-warnings
  - cargo bench --features fatal-warnings
  - cargo doc   --features fatal-warnings
  - cargo package

# TODO Do not build kcov when v34 is available, just install it directly.
after_success:
  test $TRAVIS_OS_NAME = linux
  && test $TRAVIS_RUST_VERSION = stable
  && wget https://github.com/SimonKagstrom/kcov/archive/v34.tar.gz
  && tar xzf v34.tar.gz
  && cd kcov-34
  && mkdir build
  && cd build
  && cmake ..
  && make
  && sudo make install
  && cd ../../
  && rm -rf kcov-34 v34.tar.gz
  && ./tools/codecov.sh
  && bash <(curl -s https://codecov.io/bash)
