[package]
name = "rpds"
description = "Persistent data structures for rust"
version = "0.0.0"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]


# TODO add more properties (see http://doc.crates.io/manifest.html)
homepage = "https://github.com/orium/rpds"
repository = "https://github.com/orium/rpds"
# documentation = "..."
readme = "README.md"

keywords = ["data-structures", "persistent-data-structures", "immutable-data-structures"]
categories = ["data-structures"]

license = "LGPL-3.0"

[dependencies]

[features]
fatal-warnings = []
