[package]
name = "rpds"
description = "Persistent data structures with structural sharing"
version = "0.0.0"
authors = ["Diogo Sousa <diogogsousa@gmail.com>"]

# TODO add more properties (see http://doc.crates.io/manifest.html)
homepage = "https://github.com/orium/rpds"
repository = "https://github.com/orium/rpds"
# documentation = "..."
readme = "README.md"

keywords = ["data-structures", "persistent-data-structures", "immutable-data-structures"]
categories = ["data-structures"]

license = "LGPL-3.0"

[dependencies]
# TODO This will probably be part of rust in the future (see https://github.com/rust-lang/rust/issues/29553)
bencher = "0.1"

[features]
fatal-warnings = []

[[bench]]
name = "rust_linked_list"
harness = false

[[bench]]
name = "rpds_list"
harness = false

[[bench]]
name = "rust_vec"
harness = false

[[bench]]
name = "rpds_vector"
harness = false
